Update to rust 2018 (fails to build)
Fails with:

```console
$ cargo build
   Compiling quicli-edition v0.1.0 (file:///Users/gib/tmp/quicli-edition)
error[E0463]: can't find crate for `structopt`
 --> src/main.rs:8:17
  |
8 | #[derive(Debug, StructOpt)]
  |                 ^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `quicli-edition`.

To learn more, run the command again with --verbose.
```