Update to 2021 edition, issue still reproduces
```console
❯ cargo --version
cargo 1.71.0 (cfd3bbd8f 2023-06-08)

❯ cargo build
   Compiling quicli-edition v0.1.0 (/Users/gib/code/tmp/quicli-edition)
error[E0433]: failed to resolve: could not find `structopt` in the list of imported crates
 --> src/main.rs:4:17
  |
4 | #[derive(Debug, StructOpt)]
  |                 ^^^^^^^^^ could not find `structopt` in the list of imported crates
  |
  = note: this error originates in the derive macro `StructOpt` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `quicli-edition` (bin "quicli-edition") due to previous error
```